
project_id = "dnxjhelmufqbnmvhrqtv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = false
enable_phone_confirmations = false
enable_phone_change_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[db]
enabled = true
port = 54322
shadow_port = 54323
major_version = 15

[functions]
enabled = true
port = 54325

[functions.migrate-legacy-data]
verify_jwt = false

[functions.sync-legacy-data]
verify_jwt = false

[functions.test-legacy-connection]
verify_jwt = false

[functions.test-legacy-connection-simple]
verify_jwt = false

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
