// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaoywxvfvpryaxbvaiow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphb3l3eHZmdnByeWF4YnZhaW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjg2MzQsImV4cCI6MjA2MTk0NDYzNH0.ZWA-jaOAaz8FnTgeyG_5qxVCyaFqf0S711xUzEHBVkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});